### ISSUE TITLE
Training performance

### ISSUE THREAD

**Issue by twmmason** [mbaske/ml-chord-detection#1]
Hi, awesome project here, thank you for sharing. I've been finding it hard to get anywhere near the training performance you indicated in the screenshot/video. Are you using any particular learning parameters with mlagents-learn?

**Comment by mbaske** [comment]
Thanks @twmmason - Config params are https://github.com/mbaske/ml-chord-detection/blob/main/trainer_config.yaml
Launch params for training with eight executables:  
mlagents-learn trainer_config.yaml --run-id=Chords --env=Build/AudioSensor.exe --base-port=5007 --torch-device=cpu --num-envs=8 --no-graphics --capture-frame-rate=50 --target-frame-rate=50 --time-scale=1

**Comment by twmmason** [comment]
Nice one! I think the capture > target frame rate was the culprit. Interested to tell you a bit more about what I'm using it for if it's of interest. Can I dm you?

**Comment by mbaske** [comment]
Sure, if you're on the Unity forum, you can start a private conversation there
https://forum.unity.com/members/mbaske.1629751/
or email me hello@mathias.baske.com
